
const parseString = require('xml2js').parseString;

const xml = `
<?xml version="1.0" encoding="UTF-8"?>
<letocrono_status>
    <elemento id="40" type="7" status="0" currentvalue="21.8" title="Temp. Ingresso" label_value="C" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXAuIEluZ3Jlc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="97" type="7" status="0" currentvalue="19.88" title="Temp. HT Sala Riunioni" label_value="C" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXAuIEhUIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="21" type="7" status="0" currentvalue="1427.04" title="Assorbimento Generale" label_value="W" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFzc29yYmltZW50byBHZW5lcmFsZSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="22" type="7" status="1" currentvalue="224" title="Voltaggio" label_value="v" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlZvbHRhZ2dpbyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="127" type="9" status="0" currentvalue="0" title="Monitor Stato" label_value="mV" id_group="0" currenttextvalue="Mar 21, 2022 11:57:12 AM@nConsumo Energia 2613.82 W@nMar 20, 2022 9:08:32 PM@nBatteria Button 2 sotto il 50%@nMar 20, 2022 9:07:37 PM@nPorta ingresso in Allarme@nMar 19, 2022 3:02:29 PM@nConsumo Energia 2661.81 W@nMar 19, 2022 2:50:58 PM@nPorta ingresso in Allarme@nMar 19, 2022 1:24:55 PM@nFinestra Sviluppo in Allarme@n" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk1vbml0b3IgU3RhdG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="128" type="10" status="0" currentvalue="0" title="Azzera Monitor" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF6emVyYSBNb25pdG9yIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="85" type="5" status="0" currentvalue="0" title="Porte e Finestre Chiuse" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlBvcnRlIGUgRmluZXN0cmUgQ2hpdXNlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="24" type="6" status="0" currentvalue="0" title="Apri Citofono" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFwcmkgQ2l0b2Zvbm8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="31" type="6" status="0" currentvalue="0" title="Spegni tutte le luci" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNwZWduaSB0dXR0ZSBsZSBsdWNpIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="154" type="6" status="0" currentvalue="0" title="Accendi tutte le luci" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFjY2VuZGkgVHV0dG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="32" type="2" status="0" currentvalue="0" title="Spegni tutte le luci" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJhZnRlckRheSI6IGZhbHNlLAogICJlbGVtZW50X2xhYmVsIjogIlNwZWduaSB0dXR0ZSBsZSBsdWNpIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImVuZFRpbWUiOiA4MjgwMDAwMCwKICAiZW5kVGltZVN0cmluZyI6ICIyMzowMDowMCIsCiAgImlkX2VsZW1lbnQiOiAiMzIiLAogICJzdGFydFRpbWUiOiA3OTIwMDAwMCwKICAic3RhcnRUaW1lU3RyaW5nIjogIjIyOjAwOjAwIiwKICAidXNlcl9kZWZpbmUiOiB0cnVlLAogICJ3ZWVrIjogIjE7MTsxOzE7MTsxOzEiCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="8" type="3" status="0" currentvalue="0" title="Luce Studio" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgU3R1ZGlvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiOCIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="4" type="3" status="0" currentvalue="0" title="Luce Corridoio" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgQ29ycmlkb2lvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="6" type="3" status="1" currentvalue="0" title="Luce Bagno" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgQmFnbm8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="169" type="11" status="0" currentvalue="0" title="Centrale Antifurto" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkNlbnRyYWxlIEFudGlmdXJ0byIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="9" type="11" status="0" currentvalue="0" title="Ingresso" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkluZ3Jlc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="1" type="11" status="0" currentvalue="0" title="Cucina" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkN1Y2luYSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="14" type="11" status="0" currentvalue="0" title="Sala Riunioni" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNhbGEgUml1bmlvbmkiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="17" type="11" status="0" currentvalue="0" title="Magazzino" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk1hZ2F6emlubyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="103" type="11" status="0" currentvalue="0" title="Lampadina Shelly Duo" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkxhbXBhZGluYSBTaGVsbHkgRHVvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="48" type="11" status="0" currentvalue="0" title="Porte e Finestre" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlBvcnRlIGUgRmluZXN0cmUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="98" type="11" status="0" currentvalue="0" title="Stato Sensori" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlN0YXRvIFNlbnNvcmkiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="131" type="11" status="0" currentvalue="0" title="Avvio MyShelter" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF2dmlvIE15U2hlbHRlciIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="134" type="5" status="1" currentvalue="0" title="MyShelter Avviato" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk15U2hlbHRlciBBdnZpYXRvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="138" type="11" status="0" currentvalue="0" title="Test Varie Schede" label_value="mV" id_group="0" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlc3QgVmFyaWUgU2NoZWRlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Home" />
    <elemento id="3" type="3" status="0" currentvalue="0" title="Luce Cucina" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgQ3VjaW5hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="19" type="3" status="0" currentvalue="0" title="Luce Ripostiglio New" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgUmlwb3N0aWdsaW8gTmV3IiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiMTkiLAogICJ1c2VyX2RlZmluZSI6IHRydWUKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="12" type="3" status="1" currentvalue="0" title="Frigo" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkZyaWdvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="13" type="3" status="1" currentvalue="0" title="Macchinetta Caffe" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk1hY2NoaW5ldHRhIENhZmZlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="20" type="3" status="0" currentvalue="0" title="Balcone Cucina" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhbGNvbmUgQ3VjaW5hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="29" type="2" status="1" currentvalue="0" title="Schedula macchina caffe" label_value="mV" id_group="1" currenttextvalue="" user_property="ewogICJhZnRlckRheSI6IGZhbHNlLAogICJlbGVtZW50X2xhYmVsIjogIlNjaGVkdWxhIG1hY2NoaW5hIGNhZmZlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImVuZFRpbWUiOiA3NTYwMDAwMCwKICAiZW5kVGltZVN0cmluZyI6ICIyMTowMDowMCIsCiAgImlkX2VsZW1lbnQiOiAiMjkiLAogICJzdGFydFRpbWUiOiAzMjQwMDAwMCwKICAic3RhcnRUaW1lU3RyaW5nIjogIjA5OjAwOjAwIiwKICAidXNlcl9kZWZpbmUiOiB0cnVlLAogICJ3ZWVrIjogIjA7MTsxOzE7MTsxOzEiCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="37" type="7" status="0" currentvalue="2.27" title="Assorbimento Frigo" label_value="W" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFzc29yYmltZW50byBGcmlnbyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="38" type="7" status="0" currentvalue="0.44" title="Assorbimento Macchinetta" label_value="W" id_group="1" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFzc29yYmltZW50byBNYWNjaGluZXR0YSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Cucina" />
    <elemento id="2" type="3" status="1" currentvalue="0" title="Luce Ingresso" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgSW5ncmVzc28iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="10" type="3" status="1" currentvalue="0" title="Presa profumatore" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlByZXNhIHByb2Z1bWF0b3JlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiMTAiLAogICJ1c2VyX2RlZmluZSI6IHRydWUKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="11" type="3" status="1" currentvalue="0" title="Presa Ingresso" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlByZXNhIEluZ3Jlc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="15" type="3" status="1" currentvalue="0" title="Condizionatore" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkNvbmRpemlvbmF0b3JlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="26" type="2" status="0" currentvalue="0" title="Spegni condizionatore" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJhZnRlckRheSI6IGZhbHNlLAogICJlbGVtZW50X2xhYmVsIjogIlNwZWduaSBjb25kaXppb25hdG9yZSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJlbmRUaW1lIjogNjAwMDAsCiAgImVuZFRpbWVTdHJpbmciOiAiMDA6MDE6MDAiLAogICJpZF9lbGVtZW50IjogIjI2IiwKICAic3RhcnRUaW1lIjogMCwKICAic3RhcnRUaW1lU3RyaW5nIjogIjAwOjAwOjAwIiwKICAidXNlcl9kZWZpbmUiOiB0cnVlLAogICJ3ZWVrIjogIjE7MTsxOzE7MTsxOzEiCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="27" type="2" status="0" currentvalue="0" title="Schedula Albero" label_value="mV" id_group="9" currenttextvalue="" user_property="ewogICJhZnRlckRheSI6IGZhbHNlLAogICJlbGVtZW50X2xhYmVsIjogIlNjaGVkdWxhIEFsYmVybyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJlbmRUaW1lIjogMCwKICAiZW5kVGltZVN0cmluZyI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInN0YXJ0VGltZSI6IDAsCiAgInN0YXJ0VGltZVN0cmluZyI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlLAogICJ3ZWVrIjogIiIKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="39" type="7" status="0" currentvalue="908.62" title="Consumo Clima" label_value="W" id_group="9" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkNvbnN1bW8gQ2xpbWEiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIzOSIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Ingresso" />
    <elemento id="7" type="3" status="0" currentvalue="0" title="Luce Sala Riunione" label_value="mV" id_group="14" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgU2FsYSBSaXVuaW9uZSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="16" type="3" status="1" currentvalue="0" title="Presa Sala riunione" label_value="mV" id_group="14" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlByZXNhIFNhbGEgcml1bmlvbmUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="155" type="3" status="0" currentvalue="0" title="Condizionatore" label_value="mV" id_group="14" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkNvbmRpemlvbmF0b3JlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="163" type="7" status="1" currentvalue="0" title="Assorbimento Condizionatore" label_value="w" id_group="14" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFzc29yYmltZW50byBDb25kaXppb25hdG9yZSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="156" type="11" status="0" currentvalue="0" title="RGB TV" label_value="mV" id_group="14" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJHQiBUViIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="5" type="3" status="0" currentvalue="0" title="Luce Magazzino" label_value="mV" id_group="17" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1Y2UgTWFnYXp6aW5vIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Magazzino" />
    <elemento id="18" type="3" status="0" currentvalue="0" title="Presa Magazzino Angolo" label_value="mV" id_group="17" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlByZXNhIE1hZ2F6emlubyBBbmdvbG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Magazzino" />
    <elemento id="42" type="7" status="1" currentvalue="99" title="Batteria Door" label_value="%" id_group="41" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIERvb3IiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porta Ingresso" />
    <elemento id="107" type="7" status="0" currentvalue="90" title="Luminosita'" label_value="%" id_group="41" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porta Ingresso" />
    <elemento id="43" type="5" status="1" currentvalue="1" title="Porta Ingresso" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlBvcnRhIEluZ3Jlc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="49" type="5" status="0" currentvalue="0" title="Sala Sviluppo" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNhbGEgU3ZpbHVwcG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICI0OSIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="56" type="5" status="1" currentvalue="1" title="Bagno Piccolo" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhZ25vIFBpY2NvbG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="62" type="5" status="1" currentvalue="1" title="Bagno Rack" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhZ25vIFJhY2siLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="68" type="5" status="1" currentvalue="1" title="Sala Riunioni" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNhbGEgUml1bmlvbmkiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="74" type="5" status="1" currentvalue="1" title="Studio Contabile" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlN0dWRpbyBDb250YWJpbGUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="80" type="5" status="1" currentvalue="1" title="Magazzino" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk1hZ2F6emlubyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="41" type="11" status="0" currentvalue="0" title="Porta Ingresso" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlBvcnRhIEluZ3Jlc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="50" type="11" status="0" currentvalue="0" title="Sala Sviluppo" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNhbGEgU3ZpbHVwcG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICI1MCIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="55" type="11" status="0" currentvalue="0" title="Bagno Piccolo" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhZ25vIFBpY2NvbG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="61" type="11" status="0" currentvalue="0" title="Bagno Grande RACK" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhZ25vIEdyYW5kZSBSQUNLIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="67" type="11" status="0" currentvalue="0" title="Sala Riunioni" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNhbGEgUml1bmlvbmkiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="73" type="11" status="0" currentvalue="0" title="Studio Contabile" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlN0dWRpbyBDb250YWJpbGUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="79" type="11" status="0" currentvalue="0" title="Magazzino" label_value="mV" id_group="48" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIk1hZ2F6emlubyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Porte e Finestre" />
    <elemento id="52" type="7" status="0" currentvalue="14.2" title="Temperatura" label_value="C" id_group="50" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio" />
    <elemento id="51" type="7" status="1" currentvalue="98" title="Batteria Door Studio" label_value="%" id_group="50" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio" />
    <elemento id="53" type="7" status="0" currentvalue="8810" title="Luminosita'" label_value="Lux" id_group="50" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio" />
    <elemento id="58" type="7" status="0" currentvalue="13.5" title="Temperatura" label_value="C" id_group="55" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Piccolo" />
    <elemento id="57" type="7" status="0" currentvalue="97" title="Batteria" label_value="%" id_group="55" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Piccolo" />
    <elemento id="59" type="7" status="0" currentvalue="151" title="Luminosita'" label_value="Lux" id_group="55" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Piccolo" />
    <elemento id="64" type="7" status="0" currentvalue="13.3" title="Temperatura" label_value="C" id_group="61" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Grande RACK" />
    <elemento id="63" type="7" status="0" currentvalue="98" title="Batteria" label_value="%" id_group="61" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Grande RACK" />
    <elemento id="65" type="7" status="0" currentvalue="118" title="Luminosita'" label_value="Lux" id_group="61" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Bagno Grande RACK" />
    <elemento id="70" type="7" status="0" currentvalue="13.3" title="Temperatura" label_value="C" id_group="67" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="69" type="7" status="0" currentvalue="89" title="Batteria" label_value="%" id_group="67" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="71" type="7" status="0" currentvalue="109" title="Luminosita'" label_value="Lux" id_group="67" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sala Riunioni" />
    <elemento id="76" type="7" status="0" currentvalue="14.8" title="Temperatura" label_value="C" id_group="73" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio Contabile" />
    <elemento id="75" type="7" status="0" currentvalue="97" title="Batteria" label_value="%" id_group="73" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio Contabile" />
    <elemento id="77" type="7" status="0" currentvalue="164" title="Luminosita'" label_value="Lux" id_group="73" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Studio Contabile" />
    <elemento id="82" type="7" status="0" currentvalue="14.4" title="Temperatura" label_value="C" id_group="79" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Magazzino" />
    <elemento id="81" type="7" status="0" currentvalue="81" title="Batteria" label_value="%" id_group="79" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Magazzino" />
    <elemento id="83" type="7" status="0" currentvalue="212" title="Luminosita'" label_value="Lux" id_group="79" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Magazzino" />
    <elemento id="89" type="5" status="0" currentvalue="0" title="Finestra" label_value="mV" id_group="88" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkZpbmVzdHJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="duplicare questo" />
    <elemento id="91" type="7" status="0" currentvalue="14.2" title="Temperatura" label_value="C" id_group="88" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="duplicare questo" />
    <elemento id="90" type="7" status="0" currentvalue="99" title="Batteria" label_value="%" id_group="88" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="duplicare questo" />
    <elemento id="92" type="7" status="0" currentvalue="8810" title="Luminosita'" label_value="Lux" id_group="88" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkx1bWlub3NpdGEnIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="duplicare questo" />
    <elemento id="34" type="7" status="0" currentvalue="100" title="Batteria Button 1" label_value="%" id_group="98" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIFNoZWxseSBCdXR0b24iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Stato Sensori" />
    <elemento id="99" type="7" status="1" currentvalue="47" title="Batteria Button 2" label_value="%" id_group="98" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIEJ1dHRvbiAyIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Stato Sensori" />
    <elemento id="100" type="7" status="0" currentvalue="100" title="Batteria HT Riunioni" label_value="%" id_group="98" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIEhUIFJpdW5pb25pIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Stato Sensori" />
    <elemento id="101" type="7" status="0" currentvalue="99" title="Batt. Door Porta Ingresso" label_value="%" id_group="98" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHQuIERvb3IgUG9ydGEgSW5ncmVzc28iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIxMDEiLAogICJ1c2VyX2RlZmluZSI6IHRydWUKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Stato Sensori" />
    <elemento id="102" type="7" status="0" currentvalue="98" title="Batteria Door Finestra Studio" label_value="%" id_group="98" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJhdHRlcmlhIERvb3IgRmluZXN0cmEgU3R1ZGlvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Stato Sensori" />
    <elemento id="105" type="3" status="0" currentvalue="40" title="Lampada Shelly Duo" label_value="mV" id_group="103" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkxhbXBhZGEgU2hlbGx5IER1byIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiA0MCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIxMDUiLAogICJ1c2VyX2RlZmluZSI6IHRydWUKfQ==" update_numeric_value="1" numeric_value_from_user_range="0:100" update_string_value="0" des_group="Lampadina Shelly Duo" />
    <elemento id="164" type="3" status="0" currentvalue="3958.6" title="Temperatura Luce" label_value="mV" id_group="103" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlRlbXBlcmF0dXJhIEx1Y2UiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMzk1OC42LAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIjE2NCIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="1" numeric_value_from_user_range="3000:6700" update_string_value="0" des_group="Lampadina Shelly Duo" />
    <elemento id="139" type="11" status="0" currentvalue="0" title="Shelly 4PM Pro" label_value="mV" id_group="138" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNoZWxseSA0UE0gUHJvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Test Varie Schede" />
    <elemento id="146" type="11" status="0" currentvalue="0" title="SRB001_Raimo" label_value="mV" id_group="138" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNSQjAwMV9SYWltbyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Test Varie Schede" />
    <elemento id="140" type="3" status="0" currentvalue="0" title="Relay 1" label_value="mV" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDEiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="141" type="3" status="0" currentvalue="0" title="Relay 2" label_value="mV" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDIiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="142" type="3" status="0" currentvalue="0" title="Relay 3" label_value="mV" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDMiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="143" type="3" status="0" currentvalue="0" title="Relay 4" label_value="mV" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDQiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="144" type="5" status="0" currentvalue="0" title="In1" label_value="mV" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkluMSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="145" type="7" status="1" currentvalue="0" title="Powor Out 1" label_value="W" id_group="139" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlBvd29yIE91dCAxIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Shelly 4PM Pro" />
    <elemento id="147" type="3" status="0" currentvalue="0" title="Relay 1" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDEiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="148" type="3" status="0" currentvalue="0" title="Relay 2" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDIiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="149" type="3" status="0" currentvalue="0" title="Relay 3" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDMiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="150" type="3" status="0" currentvalue="0" title="Relay 4" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDQiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="151" type="3" status="0" currentvalue="0" title="Relay 5" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="152" type="3" status="0" currentvalue="0" title="Relay 6" label_value="mV" id_group="146" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJlbGF5IDYiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="SRB001_Raimo" />
    <elemento id="158" type="3" status="0" currentvalue="84" title="Attiva RGB" label_value="mV" id_group="156" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBSR0IiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogODQsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiMTU4IiwKICAidXNlcl9kZWZpbmUiOiB0cnVlCn0=" update_numeric_value="1" numeric_value_from_user_range="0:100" update_string_value="0" des_group="RGB TV" />
    <elemento id="160" type="3" status="0" currentvalue="10" title="Rosso" label_value="mV" id_group="156" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlJvc3NvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDI1NSwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIxNjAiLAogICJ1c2VyX2RlZmluZSI6IHRydWUKfQ==" update_numeric_value="1" numeric_value_from_user_range="0:255" update_string_value="0" des_group="RGB TV" />
    <elemento id="161" type="3" status="0" currentvalue="255" title="Verde" label_value="mV" id_group="156" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlZlcmRlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDIxMi4yLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIjE2MSIsCiAgInVzZXJfZGVmaW5lIjogdHJ1ZQp9" update_numeric_value="1" numeric_value_from_user_range="0:255" update_string_value="0" des_group="RGB TV" />
    <elemento id="162" type="3" status="0" currentvalue="10" title="Blue" label_value="mV" id_group="156" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkJsdWUiLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMjUxLjYsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiMTYyIiwKICAidXNlcl9kZWZpbmUiOiB0cnVlCn0=" update_numeric_value="1" numeric_value_from_user_range="0:255" update_string_value="0" des_group="RGB TV" />
    <elemento id="193" type="3" status="0" currentvalue="0" title="Attiva Antifurto" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBBbnRpZnVydG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="209" type="2" status="0" currentvalue="0" title="Schedula Antifurto" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJhZnRlckRheSI6IGZhbHNlLAogICJlbGVtZW50X2xhYmVsIjogIlNjaGVkdWxhIEFudGlmdXJ0byIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJlbmRUaW1lIjogMTIwMDAwLAogICJlbmRUaW1lU3RyaW5nIjogIjAwOjAyOjAwIiwKICAiaWRfZWxlbWVudCI6ICIyMDkiLAogICJzdGFydFRpbWUiOiAwLAogICJzdGFydFRpbWVTdHJpbmciOiAiMDA6MDA6MDAiLAogICJ1c2VyX2RlZmluZSI6IHRydWUsCiAgIndlZWsiOiAiMTsxOzE7MTsxOzE7MSIKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="177" type="6" status="0" currentvalue="0" title="Allarme Attiva" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkFsbGFybWUgQXR0aXZhIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="172" type="11" status="0" currentvalue="0" title="Sensore Porta Ingresso" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgUG9ydGEgSW5ncmVzc28iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="178" type="11" status="0" currentvalue="0" title="Sensore Finestra Sviluppo" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU3ZpbHVwcG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="183" type="11" status="0" currentvalue="0" title="Sensore Finestra Bagno Piccolo" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgQmFnbm8gUGljY29sbyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="188" type="11" status="0" currentvalue="0" title="Sensore Finestra Bagno Grande" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgQmFnbm8gR3JhbmRlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="194" type="11" status="0" currentvalue="0" title="Sensore Finestra Sala Riunioni" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU2FsYSBSaXVuaW9uaSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="199" type="11" status="0" currentvalue="0" title="Sensore Finestra Studio" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU3R1ZGlvIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="204" type="11" status="0" currentvalue="0" title="Sensore Finestra Magazzino" label_value="mV" id_group="169" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgTWFnYXp6aW5vIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Centrale Antifurto" />
    <elemento id="170" type="5" status="0" currentvalue="0" title="Sensore Ingresso" label_value="mV" id_group="172" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgSW5ncmVzc28iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Porta Ingresso" />
    <elemento id="174" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="172" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Porta Ingresso" />
    <elemento id="179" type="5" status="0" currentvalue="0" title="Sensore Finestra Sviluppo" label_value="mV" id_group="178" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU3ZpbHVwcG8iLAogICJlbGVtZW50X25hbWUiOiAiIiwKICAiZWxlbWVudF9udW1lcmljX3ZhbHVlIjogMCwKICAiZWxlbWVudF9zdHJpbmdfdmFsdWUiOiAiIiwKICAiaWRfZWxlbWVudCI6ICIiLAogICJ1c2VyX2RlZmluZSI6IGZhbHNlCn0=" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Sviluppo" />
    <elemento id="180" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="178" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Sviluppo" />
    <elemento id="184" type="5" status="0" currentvalue="0" title="Sensore Finestra Bagno Piccolo" label_value="mV" id_group="183" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgQmFnbm8gUGljY29sbyIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Bagno Piccolo" />
    <elemento id="185" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="183" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Bagno Piccolo" />
    <elemento id="189" type="5" status="0" currentvalue="0" title="Sensore Finestra Bagno Grande" label_value="mV" id_group="188" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgQmFnbm8gR3JhbmRlIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Bagno Grande" />
    <elemento id="190" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="188" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Bagno Grande" />
    <elemento id="195" type="5" status="0" currentvalue="0" title="Sensore Finestra Sala Riunioni" label_value="mV" id_group="194" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU2FsYSBSaXVuaW9uaSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Sala Riunioni" />
    <elemento id="196" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="194" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Sala Riunioni" />
    <elemento id="200" type="5" status="0" currentvalue="0" title="Sensore Finestra Sala Riunioni" label_value="mV" id_group="199" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgU2FsYSBSaXVuaW9uaSIsCiAgImVsZW1lbnRfbmFtZSI6ICIiLAogICJlbGVtZW50X251bWVyaWNfdmFsdWUiOiAwLAogICJlbGVtZW50X3N0cmluZ192YWx1ZSI6ICIiLAogICJpZF9lbGVtZW50IjogIiIsCiAgInVzZXJfZGVmaW5lIjogZmFsc2UKfQ==" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Studio" />
    <elemento id="201" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="199" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Studio" />
    <elemento id="205" type="5" status="0" currentvalue="0" title="Sensore Finestra Magazzino" label_value="mV" id_group="204" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIlNlbnNvcmUgRmluZXN0cmEgTWFnYXp6aW5vIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Magazzino" />
    <elemento id="206" type="3" status="1" currentvalue="0" title="Attiva Zona" label_value="mV" id_group="204" currenttextvalue="" user_property="ewogICJlbGVtZW50X2xhYmVsIjogIkF0dGl2YSBab25hIiwKICAiZWxlbWVudF9uYW1lIjogIiIsCiAgImVsZW1lbnRfbnVtZXJpY192YWx1ZSI6IDAsCiAgImVsZW1lbnRfc3RyaW5nX3ZhbHVlIjogIiIsCiAgImlkX2VsZW1lbnQiOiAiIiwKICAidXNlcl9kZWZpbmUiOiBmYWxzZQp9" update_numeric_value="0" numeric_value_from_user_range="" update_string_value="0" des_group="Sensore Finestra Magazzino" />
</letocrono_status>
`;


let parsedData = null;

parseString(xml, function (err, result) {
    parsedData = result;
});




module.exports  = parsedData.letocrono_status.elemento;
